spring:
  application:
    name: job-intelligence

  datasource:
    url: jdbc:postgresql://localhost:5432/job_intelligence
    username: job_intelligence
    password: job_intelligence_dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: org.hibernate.type.format.jackson.Jackson3JsonFormatMapper

  flyway:
    enabled: true

llm:
    gemini:
      api-key : ${GEMINI_API_KEY}
      model: gemini-3.7-flash

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
job-sources:
  greenhouse:
    board-token: ${GREENHOUSE_BOARD_TOKEN}
