CREATE TABLE job_events (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            job_id BIGINT NOT NULL,

                            event_type VARCHAR(50) NOT NULL,

                            event_data JSONB,

                            occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT fk_job_events_job
                                FOREIGN KEY (job_id)
                                    REFERENCES jobs (id)
                                    ON DELETE CASCADE,

                            CONSTRAINT chk_job_events_event_type
                                CHECK (
                                    event_type IN (
                                                   'DISCOVERED',
                                                   'UPDATED',
                                                   'REQUIREMENTS_CHANGED',
                                                   'LOCATION_CHANGED',
                                                   'DESCRIPTION_CHANGED',
                                                   'STATUS_CHANGED',
                                                   'CLOSED',
                                                   'REOPENED'
                                        )
                                    )
);

CREATE INDEX idx_job_events_job_id
    ON job_events (job_id);

CREATE INDEX idx_job_events_event_type
    ON job_events (event_type);

CREATE INDEX idx_job_events_occurred_at
    ON job_events (occurred_at DESC);