INSERT INTO job_sources (
    code,
    display_name,
    source_type,
    base_url,
    enabled
)
VALUES
    (
        'GREENHOUSE',
        'Greenhouse',
        'ATS',
        'https://boards.greenhouse.io',
        TRUE
    ),
    (
        'LEVER',
        'Lever',
        'ATS',
        'https://jobs.lever.co',
        TRUE
    ),
    (
        'ASHBY',
        'Ashby',
        'ATS',
        'https://jobs.ashbyhq.com',
        TRUE
    ),
    (
        'LINKEDIN',
        'LinkedIn',
        'JOB_BOARD',
        'https://www.linkedin.com/jobs',
        TRUE
    ),
    (
        'INDEED',
        'Indeed',
        'JOB_BOARD',
        'https://www.indeed.com',
        TRUE
    ),
    (
        'NAUKRI',
        'Naukri',
        'JOB_BOARD',
        'https://www.naukri.com',
        TRUE
    ),
    (
        'WELLFOUND',
        'Wellfound',
        'JOB_BOARD',
        'https://wellfound.com',
        TRUE
    ),
    (
        'COMPANY_CAREER',
        'Company Career Page',
        'CAREER_PAGE',
        NULL,
        TRUE
    ),
    (
        'EMAIL',
        'Email Alert',
        'EMAIL',
        NULL,
        TRUE
    );