CREATE TABLE companies (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           canonical_name VARCHAR(255) NOT NULL,
                           display_name VARCHAR(255) NOT NULL,
                           website_url VARCHAR(2048),

                           created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT uq_companies_canonical_name
                               UNIQUE (canonical_name)
);