CREATE TABLE source_configurations (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                       company_id BIGINT NOT NULL,
                                       job_source_id BIGINT NOT NULL,

                                       configuration JSONB NOT NULL DEFAULT '{}'::jsonb,

                                       enabled BOOLEAN NOT NULL DEFAULT TRUE,

                                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                       CONSTRAINT fk_source_configurations_company
                                           FOREIGN KEY (company_id)
                                               REFERENCES companies (id)
                                               ON DELETE CASCADE,

                                       CONSTRAINT fk_source_configurations_job_source
                                           FOREIGN KEY (job_source_id)
                                               REFERENCES job_sources (id)
                                               ON DELETE RESTRICT,

                                       CONSTRAINT uq_source_configurations_company_source
                                           UNIQUE (company_id, job_source_id)
);

CREATE INDEX idx_source_configurations_company_id
    ON source_configurations (company_id);

CREATE INDEX idx_source_configurations_job_source_id
    ON source_configurations (job_source_id);

CREATE INDEX idx_source_configurations_enabled
    ON source_configurations (enabled);