CREATE TABLE job_sources (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             code VARCHAR(50) NOT NULL,
                             display_name VARCHAR(100) NOT NULL,
                             source_type VARCHAR(50) NOT NULL,
                             base_url VARCHAR(2048),

                             enabled BOOLEAN NOT NULL DEFAULT TRUE,

                             created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT uq_job_sources_code
                                 UNIQUE (code),

                             CONSTRAINT chk_job_sources_source_type
                                 CHECK (
                                     source_type IN (
                                                     'ATS',
                                                     'JOB_BOARD',
                                                     'CAREER_PAGE',
                                                     'EMAIL'
                                         )
                                     )
);