CREATE TABLE jobs (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                      company_id BIGINT NOT NULL,

                      title VARCHAR(500) NOT NULL,
                      normalized_title VARCHAR(500) NOT NULL,

                      description TEXT NOT NULL,

                      employment_type VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
                      seniority_level VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',

                      experience_min_years NUMERIC(4,1),
                      experience_max_years NUMERIC(4,1),

                      salary_min NUMERIC(12,2),
                      salary_max NUMERIC(12,2),
                      salary_currency CHAR(3),

                      posted_at TIMESTAMPTZ,
                      expires_at TIMESTAMPTZ,

                      canonical_application_url VARCHAR(2048),

                      canonical_fingerprint CHAR(64) NOT NULL,
                      description_hash CHAR(64),

                      status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

                      first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                      CONSTRAINT fk_jobs_company
                          FOREIGN KEY (company_id)
                              REFERENCES companies (id)
                              ON DELETE RESTRICT,

                      CONSTRAINT uq_jobs_canonical_fingerprint
                          UNIQUE (canonical_fingerprint),

                      CONSTRAINT chk_jobs_experience_range
                          CHECK (
                              experience_min_years IS NULL
                                  OR experience_max_years IS NULL
                                  OR experience_max_years >= experience_min_years
                              ),

                      CONSTRAINT chk_jobs_salary_range
                          CHECK (
                              salary_min IS NULL
                                  OR salary_max IS NULL
                                  OR salary_max >= salary_min
                              ),

                      CONSTRAINT chk_jobs_salary_currency
                          CHECK (
                              (salary_min IS NULL AND salary_max IS NULL AND salary_currency IS NULL)
                                  OR
                              (
                                  salary_currency IS NOT NULL
                                      AND salary_currency ~ '^[A-Z]{3}$'
                                  )
                              ),

                      CONSTRAINT chk_jobs_employment_type
                          CHECK (
                              employment_type IN (
                                                  'FULL_TIME',
                                                  'PART_TIME',
                                                  'CONTRACT',
                                                  'INTERNSHIP',
                                                  'TEMPORARY',
                                                  'UNKNOWN'
                                  )
                              ),

                      CONSTRAINT chk_jobs_seniority_level
                          CHECK (
                              seniority_level IN (
                                                  'INTERN',
                                                  'ENTRY',
                                                  'JUNIOR',
                                                  'MID',
                                                  'SENIOR',
                                                  'LEAD',
                                                  'STAFF',
                                                  'UNKNOWN'
                                  )
                              ),

                      CONSTRAINT chk_jobs_status
                          CHECK (
                              status IN (
                                         'ACTIVE',
                                         'CLOSED',
                                         'EXPIRED',
                                         'UNKNOWN'
                                  )
                              )
);

CREATE INDEX idx_jobs_company_id
    ON jobs (company_id);

CREATE INDEX idx_jobs_posted_at
    ON jobs (posted_at);

CREATE INDEX idx_jobs_status
    ON jobs (status);

CREATE INDEX idx_jobs_last_seen_at
    ON jobs (last_seen_at);

CREATE UNIQUE INDEX uq_jobs_application_url
    ON jobs (canonical_application_url)
    WHERE canonical_application_url IS NOT NULL;