CREATE TABLE job_source_listings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     job_id BIGINT NOT NULL,
                                     job_source_id BIGINT NOT NULL,

                                     external_job_id VARCHAR(255),
                                     source_url VARCHAR(2048) NOT NULL,

                                     raw_payload JSONB,

                                     source_posted_at TIMESTAMPTZ,

                                     discovered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     is_active BOOLEAN NOT NULL DEFAULT TRUE,

                                     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT fk_job_source_listings_job
                                         FOREIGN KEY (job_id)
                                             REFERENCES jobs (id)
                                             ON DELETE CASCADE,

                                     CONSTRAINT fk_job_source_listings_source
                                         FOREIGN KEY (job_source_id)
                                             REFERENCES job_sources (id)
                                             ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_job_source_listings_external_id
    ON job_source_listings (job_source_id, external_job_id)
    WHERE external_job_id IS NOT NULL;

CREATE INDEX idx_job_source_listings_job_id
    ON job_source_listings (job_id);

CREATE INDEX idx_job_source_listings_source_id
    ON job_source_listings (job_source_id);

CREATE INDEX idx_job_source_listings_last_seen_at
    ON job_source_listings (last_seen_at);

CREATE INDEX idx_job_source_listings_active
    ON job_source_listings (is_active);