CREATE TABLE job_locations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               job_id BIGINT NOT NULL,

                               city VARCHAR(150),
                               state VARCHAR(150),
                               country VARCHAR(150),

                               remote_type VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',

                               display_text VARCHAR(500) NOT NULL,

                               created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_job_locations_job
                                   FOREIGN KEY (job_id)
                                       REFERENCES jobs (id)
                                       ON DELETE CASCADE,

                               CONSTRAINT chk_job_locations_remote_type
                                   CHECK (
                                       remote_type IN (
                                                       'ONSITE',
                                                       'HYBRID',
                                                       'REMOTE',
                                                       'UNKNOWN'
                                           )
                                       )
);

CREATE INDEX idx_job_locations_job_id
    ON job_locations (job_id);

CREATE INDEX idx_job_locations_country
    ON job_locations (country);

CREATE INDEX idx_job_locations_city
    ON job_locations (city);

CREATE INDEX idx_job_locations_remote_type
    ON job_locations (remote_type);