CREATE TABLE job_requirements (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  job_id BIGINT NOT NULL,

                                  requirement_type VARCHAR(50) NOT NULL,

                                  value VARCHAR(500) NOT NULL,
                                  normalized_value VARCHAR(500) NOT NULL,

                                  is_mandatory BOOLEAN NOT NULL DEFAULT FALSE,

                                  years_required NUMERIC(4,1),

                                  requirement_text TEXT,

                                  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                  CONSTRAINT fk_job_requirements_job
                                      FOREIGN KEY (job_id)
                                          REFERENCES jobs (id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT chk_job_requirements_type
                                      CHECK (
                                          requirement_type IN (
                                                               'TECHNOLOGY',
                                                               'LANGUAGE',
                                                               'EDUCATION',
                                                               'EXPERIENCE',
                                                               'CERTIFICATION',
                                                               'OTHER'
                                              )
                                          ),

                                  CONSTRAINT chk_job_requirements_years
                                      CHECK (
                                          years_required IS NULL
                                              OR years_required >= 0
                                          )
);

CREATE INDEX idx_job_requirements_job_id
    ON job_requirements (job_id);

CREATE INDEX idx_job_requirements_type
    ON job_requirements (requirement_type);

CREATE INDEX idx_job_requirements_normalized_value
    ON job_requirements (normalized_value);

CREATE INDEX idx_job_requirements_mandatory
    ON job_requirements (is_mandatory);