CREATE TABLE candidate_profiles (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                    name VARCHAR(255) NOT NULL,
                                    email VARCHAR(320) NOT NULL,

                                    current_location VARCHAR(255),

                                    preferred_locations JSONB,
                                    preferred_work_modes JSONB,

                                    minimum_salary NUMERIC(12,2),
                                    minimum_salary_currency CHAR(3),

                                    willing_to_relocate BOOLEAN NOT NULL DEFAULT FALSE,

                                    is_active BOOLEAN NOT NULL DEFAULT TRUE,

                                    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                    CONSTRAINT uq_candidate_profiles_email
                                        UNIQUE (email),

                                    CONSTRAINT chk_candidate_profiles_salary_currency
                                        CHECK (
                                            (minimum_salary IS NULL AND minimum_salary_currency IS NULL)
                                                OR
                                            (
                                                minimum_salary IS NOT NULL
                                                    AND minimum_salary_currency IS NOT NULL
                                                    AND minimum_salary_currency ~ '^[A-Z]{3}$'
                                                )
                                            )
);

CREATE INDEX idx_candidate_profiles_active
    ON candidate_profiles (is_active);