CREATE TABLE candidate_skills (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  candidate_profile_id BIGINT NOT NULL,

                                  skill VARCHAR(255) NOT NULL,
                                  normalized_skill VARCHAR(255) NOT NULL,

                                  proficiency VARCHAR(30),
                                  years_experience NUMERIC(4,1),

                                  is_primary BOOLEAN NOT NULL DEFAULT FALSE,

                                  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                  CONSTRAINT fk_candidate_skills_candidate
                                      FOREIGN KEY (candidate_profile_id)
                                          REFERENCES candidate_profiles (id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT chk_candidate_skills_years
                                      CHECK (
                                          years_experience IS NULL
                                              OR years_experience >= 0
                                          ),

                                  CONSTRAINT uq_candidate_skills_candidate_skill
                                      UNIQUE (candidate_profile_id, normalized_skill)
);

CREATE INDEX idx_candidate_skills_candidate_id
    ON candidate_skills (candidate_profile_id);

CREATE INDEX idx_candidate_skills_normalized_skill
    ON candidate_skills (normalized_skill);

CREATE INDEX idx_candidate_skills_primary
    ON candidate_skills (is_primary);