CREATE TABLE job_matches (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             job_id BIGINT NOT NULL,
                             candidate_profile_id BIGINT NOT NULL,

                             hard_qualified BOOLEAN NOT NULL,

                             skill_score NUMERIC(5,2),
                             experience_score NUMERIC(5,2),
                             role_score NUMERIC(5,2),
                             location_score NUMERIC(5,2),
                             salary_score NUMERIC(5,2),
                             semantic_score NUMERIC(5,2),

                             final_score NUMERIC(5,2) NOT NULL,

                             match_reasoning TEXT,

                             llm_provider VARCHAR(50),
                             llm_model VARCHAR(100),
                             llm_prompt_version VARCHAR(50),

                             evaluated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT fk_job_matches_job
                                 FOREIGN KEY (job_id)
                                     REFERENCES jobs (id)
                                     ON DELETE CASCADE,

                             CONSTRAINT fk_job_matches_candidate
                                 FOREIGN KEY (candidate_profile_id)
                                     REFERENCES candidate_profiles (id)
                                     ON DELETE CASCADE,

                             CONSTRAINT uq_job_matches_job_candidate
                                 UNIQUE (job_id, candidate_profile_id),

                             CONSTRAINT chk_job_matches_scores
                                 CHECK (
                                     (skill_score IS NULL OR skill_score BETWEEN 0 AND 100)
                                         AND
                                     (experience_score IS NULL OR experience_score BETWEEN 0 AND 100)
                                         AND
                                     (role_score IS NULL OR role_score BETWEEN 0 AND 100)
                                         AND
                                     (location_score IS NULL OR location_score BETWEEN 0 AND 100)
                                         AND
                                     (salary_score IS NULL OR salary_score BETWEEN 0 AND 100)
                                         AND
                                     (semantic_score IS NULL OR semantic_score BETWEEN 0 AND 100)
                                         AND
                                     final_score BETWEEN 0 AND 100
                                     )
);

CREATE INDEX idx_job_matches_job_id
    ON job_matches (job_id);

CREATE INDEX idx_job_matches_candidate_id
    ON job_matches (candidate_profile_id);

CREATE INDEX idx_job_matches_final_score
    ON job_matches (final_score DESC);

CREATE INDEX idx_job_matches_evaluated_at
    ON job_matches (evaluated_at DESC);

CREATE INDEX idx_job_matches_qualified
    ON job_matches (hard_qualified);